name: Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out 🛎
        uses: actions/checkout@v3

      - name: Set Node 🔧
        uses: actions/setup-node@1
        with:
          node-version: 17.x

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependencies 🧑‍💻
        run: yarn install --frozen-lockfile

      - name: Generate 🏭
        run: yarn generate

      - name: Archive Artifact 📮
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Download Artifact 📬
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Deploy to Netlify 🚀
        run: npx netlify-cli deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
